function init -a path --on-event ssh-config.d
  config ssh-config.d --set ssh_config ~/.ssh/config
  config ssh-config.d --set ssh_config_dir ~/.ssh/config.d/
  config ssh-config.d --set warn \
"# ssh-config.d: This ssh config file was automatically generated by
# ssh-config.d: ssh-config.d fish plugin from *.config files, located in
# ssh-config.d: ~/.ssh/config.d/. All changes will be overwritten without
# ssh-config.d: backup on following ssh execution. To change this behaviour
# ssh-config.d: (enable backup), delete all lines, containing 'ssh-config.d'.

"
end
